### PR TITLE
Form template

### PR DESCRIPTION
**Pull request by jittaearn**
I have edited the form page. Along with adding the instruction on how to add more questions to a topic. If you found it hard to understand please inform me. Otherwise, if there are any suggestions please leave a comment below. Thank you.

### CODE REVIEW

**Comment by magmagcup** [comment]
Approve

**Comment by jittaearn** [comment]
Please review the work again. I have moved the styling in the Html file to the CSS.

**Comment by Champ2k** [comment]
Approved

**Comment by MaquiaSA** [comment]
Nice template. Approve

**Pull request merged**
