### PR TITLE
Game page

### PR DESCRIPTION
**Pull request by MaquiaSA**
Player can play the game until the end, save score into database. Also provide Form Preview when player add more question for each topic.

Main Game includes
- Topic Selection page
   - List of all game Topic available.
- Main Game page
   - Redirect from Topic Selection page.
   - Each question shows
      - Countdown Timer for all question (20mins)
      - Difficulty of each question
      - Article with input field(*)
      - Next question button
(* Each input field's size depends on the length of the answer.)

After finish all questions, the score will be saved to the database.

### CODE REVIEW

**Comment by magmagcup** [comment]
There are conflicts in .gitignore  please fix it before merging.

**Comment by magmagcup** [comment]
Fix it, merge approve.

**Comment by Champ2k** [comment]
Approved

**Comment by jittaearn** [comment]
Looks good, approved.

**Comment by magmagcup** [comment]
Merge approve

**Comment by jittaearn** [comment]
Approve pull request.

**Pull request merged**
